language: php

php:
  - 5.3.3
  - 5.3
  - 5.4

before_script:
  composer install -n
  echo 'extension = php_openssl.dll' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script: phpunit -c app/
