imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @VelesHomeWorkBundle/Resources/config/services.xml }
    - { resource: @VelesHomeWorkBundle/Resources/config/admin.xml }

framework:
    #esi:             ~
    translator: ~
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ VelesHomeWorkBundle, FOSCommentBundle ]
    read_from:      %kernel.root_dir%/Resources/views/
    write_to:       %kernel.root_dir%/../web/

    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #yui_js:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        #    apply_to: "\.js"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        #    apply_to: "\.css"

    assets:
        bootstrap_min_css:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/css/bootstrap.min.css
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/css/bootstrap-theme.min.css
            filters:
                - cssrewrite
            output: css/bootstrap.min.css

        jquery_min_js:
            inputs:
                - %kernel.root_dir%/../vendor/components/jquery/jquery.min.js
            output: js/jquery.min.js

        bootstrap_min_js:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/js/bootstrap.min.js
            output: js/bootstrap.min.js

fos_comment:
    db_driver: orm
    class:
        model:
            comment: Veles\HomeWorkBundle\Entity\Comment
            thread: Veles\HomeWorkBundle\Entity\Thread

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Veles\UserBundle\Entity\User

    service:
        mailer: fos_user.mailer.twig_swift

    registration:
        confirmation:
            enabled:    true

            from_email:
                address:        robot@blog.loc
                sender_name:    Veles Blog Registration

    resetting:
        email:
            from_email:
                address:        robot@blog.loc
                sender_name:    Veles Blog Resetting


sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]

        # Your other blocks
        #sonata.admin_doctrine_orm.block.audit:
        #    contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.rss:

        # Some specific block from the SonataMediaBundle
        #sonata.media.block.media:
        #sonata.media.block.gallery:
        #sonata.media.block.feature_media:

sonata_admin:
    title:      Veles HomeWork Bundle
    title_logo: bundles/veleshomework/images/veles_logo.png

    #security:
    #    handler: sonata.admin.security.handler.role
    #    acl_user_manager: fos_user.user_manager # Name of the user manager service used to retrieve ACL users

    options:
        html5_validate: false # does not use html5 validation
        confirm_exit:   false # disable confirmation when quitting with unsaved changes
        pager_links:    5     # pager max links to display

    # set to true to persist filter settings per admin module in the user's session
    persist_filters: false

knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: knp_menu.html.twig
    templating: false # if true, enables the helper for PHP templates
    default_renderer: twig # The renderer to use, list is also available by default

liip_imagine:
    filter_sets:
        my_thumb:
            quality: 100
            filters:
                thumbnail: { size: [110, 110], mode: outbound }
        big_thumb:
            quality: 100
            filters:
                thumbnail: { size: [250, 250], mode: outbound }
        min_thumb:
            quality: 100
            filters:
                thumbnail: { size: [50, 50], mode: outbound }

vlabs_media:
    image_cache:
        cache_dir: media/cache
    mapping:
        image_entity:
          class: Veles\HomeWorkBundle\Entity\Image

stof_doctrine_extensions:
    orm:
        default:
            timestampable: true
            sluggable: true

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    disable_delivery:  false
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    port:      %mailer_port%
    encryption: %mailer_encryption%
    spool:     { type: memory }
